- name: Create ArgoCD namespace
  command: kubectl create namespace argocd
  ignore_errors: yes

- name: Install ArgoCD CRDs
  command: kubectl create -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  ignore_errors: yes
