name: Build and Push Node-RED Image

on:
  push:
    paths:
      - 'node-red/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodered:latest ./node-red

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodered:latest
